##미분 : 변수의 움직임에 따른 함수값의 변화를 측정하기 위한 도구

In [1]:
import sympy as sym
from sympy.abc import x

sym.diff(sym.poly(x**2 + 2*x + 3), x)

Poly(2*x + 2, x, domain='ZZ')

#한 점에서 접선의 기울기를 알면 어느 방향으로 점을 움직여야 함수값이 증가/감소 하는지 알 수 있다

변수가 벡터일 경우? 벡터는 n차원 공간에서의 한 점이기 때문에, 이동을 할 때 많은 방향으로 이동할 수 있다

그래서 특정 방향의 좌표축으로 이동하는 미분을 정의하는데, 이게 편미분이다.



In [3]:
#편미분
# 벡터가 입력인 다변수 함수의 경우 편미분을 사용한다.
from sympy.abc import x,y
sym.diff(sym.poly(x**2 + 2*x*y + 3) + sym.cos(x+2*y), x)

2*x + 2*y - sin(x + 2*y)

# 각 변수별로 편미분을 계산한 결과값을 그레디언트 벡터라 부르고

역삼각형 f 기호 = nabla = 주어진 다 변수를 입력으로 가지는 함수의 그레디언트 벡터를 표시하는 기호



#경사하강법 기반 선형회귀 알고리즘

In [26]:
import numpy as np
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(x, np.array([1,2])) + 3 #계수 1,2,3   1*x1 + 2*x2 + 3  해당 계수 1,2,3을 찾으면 됨

In [27]:
y # 정답

array([ 6,  8,  9, 11])

In [28]:
beta_gd = [10.1, 15.1, -6.5] # 
X_ = np.array([np.append(x,[1]) for x in X]) #intercept 항을 추가

In [29]:
X_

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 1],
       [2, 3, 1]])

In [30]:
beta_gd

[10.1, 15.1, -6.5]

In [32]:
for t in range(50000):
    error = y - X_ @ beta_gd
    grad = -np.transpose(X_) @ error #np.transpose(X_) : beta_gd에 대해 편미분한 결과값
    beta_gd = beta_gd - 0.01 * grad

print(beta_gd)

[1. 2. 3.]


##확률적 경사하강법은 모든 데이터(모든 벡터)를 사용해서 업데이트 하는 경사하강법 대신.

# 데이터 한개 또는 일부 데이터(일부 벡터)를 사용해서 gradient를 업데이트 한다.

# non convex 목적식은 SGD(확률적경사하강법)을 통해 최적화 가능하다