In [51]:
import numpy as np
test_array = np.array([1,4,5,8], float)
print(test_array)

[1. 4. 5. 8.]


numpy는 np.array 함수를 활용해서 배열을 생성한다. ndarray : 객체

하나의 데이터 타입만 배열에 넣을 수 있음  파이썬의 리스트처럼 [1,0.7,0.5] 이렇게 못 넣는다.

--> 즉 다이나믹 타이핑이 지원되지 않는다

In [52]:
type(test_array), type(test_array[3])

(numpy.ndarray, numpy.float64)

## 메모리 참조에 있어서 파이썬 리스트와 넘파이 차이점

파이썬 리스트는 value값이 있는 메모리값을 참조하여 그 값을 가르키고 있기 때문에.

정적 메모리에 위치한 값을 가르키게 된다면, 주소 값이 아래처러 같다

In [53]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

a[0] is b[-1]

True

In [54]:
id(a[0]), id(b[-1])

(10914496, 10914496)

아래는 어레이를 비교한 예시인데, 어레이는 stack처럼 값을 쌓아서 관리하기 때문에

메모리 주소가 흩어져있지 않아서, 예측 가능하다

In [131]:
c = np.array(a)
d = np.array(b)

c[0] is d[-1]

False

In [132]:
id(c), id(d)

(140465202538976, 140465202538896)

In [56]:
c[0],d[-1]

(1, 1)

In [129]:
id(c[0]), id(d[-1]) # 이 부분 이해가 잘 안가네. c[0] is d[-1]이 false인데, 주소값은 같다?

(140465202525528, 140465202525528)

numpy dtype

In [58]:
a = np.array([[1,2,3], [4.5, 5, 6]], dtype=np.int8)

In [59]:
a.dtype

dtype('int8')

In [60]:
# 8bit = 1byte.   float32 : 32bits = 4bytes  /  숫자 하나당 4bytes
np.array([[1,2,3], [4.5, 5, 6]], dtype=np.float32).nbytes

24

In [61]:
# 8bit = 1byte.  int32 : 32bits = 4bytes  / 숫자 하나당 4 bytes
np.array([[1,2,3], [4.5, 5, 6]], dtype=np.int32).nbytes

24

In [62]:
# 8bits = 1 byte,   int8 : 숫자 하나를 8비트로 표현 
np.array([[1,2,3], [4.5, 5, 6]], dtype=np.int8).nbytes

6

In [63]:
np.array([[1,2,3], [4.5, 5, 6]], dtype=np.float64).nbytes

48

##Indexing slicing

In [64]:
test = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
test[1] # 1차원으로 나옴

array([ 6,  7,  8,  9, 10])

In [66]:
test[1:2] # 2차원으로 표현됨

array([[ 6,  7,  8,  9, 10]])

In [67]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [69]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [70]:
arr[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [71]:
arr[::2,::3]

array([[ 0,  3],
       [10, 13]])

## eye, identity, digonal

In [72]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [73]:
np.eye(N=3, M=5, k=2, dtype=np.int8)  # k는 1이 시작될 열을 지정해줌

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [74]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [76]:
matrix = np.arange(12).reshape(3,4)

In [77]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
#대각 행렬 구하기 diag

np.diag(matrix, k=2)

array([2, 7])

In [79]:
np.diag(matrix, k=-1)

array([4, 9])

In [80]:
np.diag(matrix, k=0)

array([ 0,  5, 10])

In [81]:
np.random.normal(0,1,10).reshape(2,5)

array([[-2.27717788, -0.56217291,  0.48593262,  0.14759448, -0.25819946],
       [ 0.61311571,  1.69866773, -0.7464101 ,  0.36975197,  0.37852496]])

In [84]:
np.random.exponential(scale=2, size=100)

array([ 0.50890283,  1.33095826,  3.00239408,  2.36931154,  3.44460303,
        2.69018744,  0.03491174,  0.02866099,  0.35323394,  1.45218058,
        2.53275831,  0.62288833,  0.06880427,  1.47670782,  1.96213955,
        2.25717027,  0.73956826,  0.89435372,  1.18617359,  1.97917162,
        2.75631765,  2.05606759,  3.01745629,  5.9737649 ,  2.65087225,
        1.02642839,  1.87845056,  0.54999954,  4.85493467,  2.13922915,
        1.35349464,  4.59851299,  2.91883558,  2.7453718 ,  8.00239858,
        1.90559174,  4.60367883,  0.28364852,  0.05819679,  0.8022709 ,
        4.74967658,  0.67150834,  2.46969171,  2.27878044,  1.12131351,
        0.15415998,  2.42026528,  0.20388257,  2.27461665,  3.30313245,
        0.26002176,  0.51898818,  1.30736747,  2.64622263,  2.0393969 ,
        1.7855757 ,  4.43953679,  1.07276443,  0.81013981,  0.62721323,
        5.86554928,  0.46502271,  0.3620594 ,  3.9439579 , 10.83774414,
        2.38197576,  1.51035331,  5.07219076,  1.72725912,  1.65

# concatenate

In [85]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [86]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
a = np.array([1,2,3])
b = np.array([2,3,4])

np.concatenate((a,b), axis=0)

array([1, 2, 3, 2, 3, 4])

In [88]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [89]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])

np.concatenate((a,b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [90]:
a = np.array([[1,2], [3,4]])
b = np.array([[5], [6]])

In [91]:
a

array([[1, 2],
       [3, 4]])

In [92]:
b

array([[5],
       [6]])

In [93]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [94]:
np.concatenate((a,b), axis=0)

ValueError: ignored

In [95]:
a = np.array([[1,2], [3,4]])
b = np.array([5,6])

In [96]:
b.reshape(-1,2)

array([[5, 6]])

In [102]:
b = np.array([5,6])
b[np.newaxis, :]

array([[5, 6]])

In [103]:
b = b[np.newaxis, :]
b

array([[5, 6]])

In [105]:
b.T

array([[5],
       [6]])

In [106]:
a

array([[1, 2],
       [3, 4]])

In [107]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#argmax & argmin

In [108]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [109]:
a.argsort() #정렬된 인덱스 뽑아주기

array([0, 1, 7, 2, 3, 4, 6, 5])

In [110]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0])

In [112]:
np.argmax(a), a[np.argmax(a)]

(5, 78)

In [113]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [114]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

#boolean index

In [115]:
test_array = np.array([1,4,0,2,33,8,9,7], float)
test_array > 3

array([False,  True, False, False,  True,  True,  True,  True])

In [116]:
condition = test_array<3
test_array[condition]

array([1., 0., 2.])

##fancy index

In [117]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 인덱스로 쓰는거라 반드시 인티져

In [119]:
a,b

(array([2., 4., 6., 8.]), array([0, 0, 1, 3, 2, 1]))

In [120]:
a[b]

array([2., 2., 4., 8., 6., 4.])

In [121]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [122]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [125]:
condition = c

In [126]:
a.take(condition)

array([1., 4., 4., 4., 4.])

In [127]:
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])